- name: Déployer MySQL sur la VM
  hosts: myhosts
  become: true
  tasks:

    - name: Assurer que Docker est installé
      package:
        name: docker-ce
        state: present

    - name: Démarrer le service Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Lancer le conteneur MySQL avec volume temporaire
      community.docker.docker_container:
        name: mysql_db
        image: mysql:8
        state: started
        restart_policy: unless-stopped
        env:
          MYSQL_ROOT_PASSWORD: root
        tmpfs:
          - /var/lib/mysql
        published_ports:
          - "3306:3306"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          retries: 5
